### ISSUE TITLE
TypeError: Object #<Object> has no method 'apply'

### ISSUE THREAD

**Issue by cowwoc** [teambition/gulp-sequence#1]
Given:

```
gulp.task("fileChanged", function()
{
    // Try to access a non-existent object "event"
    webpack.watch(event.path, webpackOptions,
    {
        base: path.resolve(event.path)
    }, function(err, stats)
    {
        // ...
    });
}

gulp.task("watch", ["browser-sync"], function()
{
    gulp.watch(buildConfig.srcDir + "**/*.js", ["javascript"]).on("change", sequence("fileChanged"));
    gulp.watch(buildConfig.srcDir + "**/*.scss").on("change", sequence("fileChanged", "css"));
});
gulp.task("default", ["watch"]);
```

I am getting:

```
[14:20:35] ReferenceError: event is not defined
    at Gulp.<anonymous> (d:\Users\Gili\Documents\realestate\frontend\Gulpfile.js:94:16)
    at module.exports (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp-sequence\index.js:63:12
    at tryRun (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp-sequence\node_modules\thunks\thunks.js:63:22)
    at runThunk (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp-sequence\node_modules\thunks\thunks.js:84:11)
    at d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp-sequence\node_modules\thunks\thunks.js:147:49
    at tryRun (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp-sequence\node_modules\thunks\thunks.js:63:22)

d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp-sequence\node_modules\thunks\thunks.js:47
      throw err;
            ^
TypeError: Object #<Object> has no method 'apply'
    at tryRun (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp-sequence\node_modules\thunks\thunks.js:63:22)
    at callback (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp-sequence\node_modules\thunks\thunks.js:191:24)
    at next (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp-sequence\node_modules\thunks\thunks.js:150:33)
    at Gulp.errorListener (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp-sequence\index.js:48:11)
    at Gulp.emit (events.js:117:20)
    at Gulp.Orchestrator._emitTaskDone (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp\node_modules\orchestrator\index.js:264:8)
    at d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp\node_modules\orchestrator\index.js:275:23
    at finish (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:21:8)
    at module.exports (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:36:10)
    at Gulp.Orchestrator._runTask (d:\Users\Gili\Documents\realestate\frontend\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
```

It looks like https://github.com/teambition/gulp-sequence/blob/master/index.js#L48 does not contain the kind of value you expect.

**Comment by zensh** [comment]
`fileChanged` task has a mistake, you should use `callback`:

``` js
gulp.task("fileChanged", function(callback)
{
    // Try to access a non-existent object "event"
    webpack.watch(event.path, webpackOptions,
    {
        base: path.resolve(event.path)
    }, function(err, stats)
    {
        // ...
        callback(err)
    });
}
```

**Comment by cowwoc** [comment]
@zensh I understand that the task has a mistake (I acknowledged as much above). My point is that buggy user code should not cause the `gulp-sequence` plugin to crash. It should catch and recover from this kind of exception (print an error message and shut down gracefully).

**Comment by zensh** [comment]
I will improve it, and update for gulp v4

**Comment by zensh** [comment]
Hi, @cowwoc, `watch` task should write in this way:

``` js
gulp.task("watch", ["browser-sync"], function()
{
    gulp.watch(buildConfig.srcDir + "**/*.js", ["javascript"]).on("change", function() {
      sequence("fileChanged")();
    });
    gulp.watch(buildConfig.srcDir + "**/*.scss").on("change", function() {
      sequence("fileChanged", "css")();
    });
});
```

`sequence` return a `thunk` function that expect a callback as argument, `change` event listener called it with event object~, `Object #<Object> has no method 'apply'`.

**Comment by cowwoc** [comment]
Got it. Were any commits applied against improving error handling? I ask because I don't see any references attached to this issue.

**Comment by zensh** [comment]
[thunks@2.7.2](https://github.com/thunks/thunks), will throw a TypeError

**Comment by cowwoc** [comment]
Sounds good. Feel free to close this issue.
