### ISSUE TITLE
TypeError: gulp.on(...).start is not a function

### ISSUE THREAD

**Issue by cagcak** [teambition/gulp-sequence#14]
I have a task like below, which includes working tasks:
```
gulp.task('deploy', gulpSequence(
    'task-9',
    [
        'task-1',
        'task-2',
        'task-3',
        'task-4',
        'task-5',
        'task-6',
    ],
    'task-11'
))
```

I tried all three use cases, but no luck. Below lines are error logs:
```
[16:10:44] TypeError: gulp.on(...).on(...).on(...).on(...).start is not a function
    at /home/my-project/node_modules/gulp-sequence/index.js:68:12
    at apply (/home/my-project/node_modules/thunks/index.js:354:38)
    at tryRun (/home/my-project/node_modules/thunks/index.js:224:19)
    at runThunk (/home/my-project/node_modules/thunks/index.js:217:15)
    at /home/my-project/node_modules/thunks/index.js:314:49
    at apply (/home/my-project/node_modules/thunks/index.js:354:38)
    at tryRun (/home/my-project/node_modules/thunks/index.js:224:19)
    at runThunk (/home/my-project/node_modules/thunks/index.js:217:15)
    at continuation (/home/my-project/node_modules/thunks/index.js:164:10)
    at child (/home/my-project/node_modules/thunks/index.js:155:24)
```

I could not understand the issue. Any idea ?

**Comment by zensh** [comment]
Sorry, It can't support gulp v4~

**Comment by cagcak** [comment]
ok. thanks. 
I turned that into: 
```
gulp.task('deploy', gulp.series(
    'task-9',
    gulp.parallel(
        'task-1',
        'task-2',
        'task-3',
        'task-4',
        'task-5',
        'task-6',
    ),
    'task-11'
))
```
