### ISSUE TITLE
Error: thunk already filled on subsequent run

### ISSUE THREAD

**Issue by ccnokes** [teambition/gulp-sequence#2]
I've been running into an issue where the plugin occasionally throws a "thunk already filled error". I think it usually happens the second subsequent time its run during a watch, not the first. 

Here's my code:

```
gulp.task('viewSeq', gulpSequence('copyViews', ['createTmplCache', 'cleanScripts'], 'scripts'));

gulp.task('watch', function() {
    livereload.listen();
    gulp.watch(srcPaths.views, ['viewSeq']);
});
```

And here's the stacktrace:

```
Error: The thunk already filled
    at child (/Users/cameronnokes/Repositories/detectiveui-temp/node_modules/gulp-sequence/node_modules/thunks/thunks.js:217:32)
    at Gulp.<anonymous> (/Users/cameronnokes/Repositories/detectiveui-temp/node_modules/gulp-sequence/node_modules/thunks/thunks.js:212:14)
    at module.exports (/Users/cameronnokes/Repositories/detectiveui-temp/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/cameronnokes/Repositories/detectiveui-temp/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/cameronnokes/Repositories/detectiveui-temp/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/cameronnokes/Repositories/detectiveui-temp/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at Gulp.<anonymous> (/Users/cameronnokes/Repositories/detectiveui-temp/node_modules/gulp/index.js:36:18)
    at Gaze.<anonymous> (/Users/cameronnokes/Repositories/detectiveui-temp/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/index.js:18:14)
    at Gaze.emit (events.js:98:17)
    at Gaze.emit (/Users/cameronnokes/Repositories/detectiveui-temp/node_modules/gulp/node_modules/vinyl-fs/node_modules/glob-watcher/node_modules/gaze/lib/gaze.js:129:32)
```

I tried googling it and nothing turned up. Is there something about my setup or syntax that's wrong? Let me know if you need more details.

**Comment by zensh** [comment]
gulpSequence return thunk function that could only run once.

Modify code: 

``` js
gulp.task('viewSeq', function(callback) {
  gulpSequence('copyViews', ['createTmplCache', 'cleanScripts'], 'scripts')(callback)
});

gulp.task('watch', function() {
    livereload.listen();
    gulp.watch(srcPaths.views, ['viewSeq']);
});
```

**Comment by ccnokes** [comment]
That does it. Thanks!

**Comment by xdemocle** [comment]
if viewSeq task is a dependency of another gulp task, this parent task will not wait the end of viewSeq, cause there is no stream available when running gulpSequence inside it.

EDIT: ok, it works. Was my fault cause the reload of the page was happening before another task finish to write a file on disk.
